---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: harness-delegate-ng
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "webapp"
        }
        "mount_path" = "auth/aks-auth"
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/tmp/vault/sink"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    "vault" = {
      "address" = "http://vault.vault.svc.cluster.local:8200"
    }

  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "webapp"
        }
        mount_path = "auth/aks-auth"
        "type" = "kubernetes"
      }
      "sink" = {
        "config" = {
          "path" = "/tmp/vault/sink"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      contents = <<EOT
        {{- with secret "secret/data/tooling_secrets" -}}
          {{ range $k, $v := .Data.data }}
            export {{ $k }}={{ $v }}
          {{ end }}
        {{- end }}
      EOT

      "destination" = "/vault/secrets/harness-secret"
    }

    "vault" = {
      "address" = "http://vault.vault.svc.cluster.local:8200"
    }
