---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: app-example

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-example1
  template:
    metadata:
      labels:
        app: app-example1
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        # vault.hashicorp.com/secret-volume-path: '/tmp/vault'
        vault.hashicorp.com/agent-copy-volume-mounts: 'app'
        vault.hashicorp.com/agent-inject-secret-db-creds: secret/data/database/creds/db-app
        vault.hashicorp.com/log-level: trace
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "secret/data/database/creds/db-app" -}}
          postgres://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/appdb?sslmode=disable
          {{- end }}
        # vault.hashicorp.com/agent-inject-command-tooling: |
        # vault.hashicorp.com/tls-secret: 'vault-tls-client'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/auth-path: 'auth/aks-auth'
    spec:
      containers:
        - name: app
          image: 'nginx:latest'
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: shared-secrets
            - mountPath: /tmp/vault
              name: vault-sink

      serviceAccountName: default
      volumes:
      - emptyDir:
          medium: Memory
        name: shared-secrets
      - emptyDir:
          medium: Memory
        name: vault-sink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-example
  template:
    metadata:
      labels:
        app: app-example
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-configmap: 'my-configmap'
        # vault.hashicorp.com/secret-volume-path: '/tmp/vault'
        vault.hashicorp.com/agent-copy-volume-mounts: 'app'
        vault.hashicorp.com/agent-inject-secret-db-creds: secret/data/database/creds/db-app
        vault.hashicorp.com/log-level: trace
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/db-app" -}}
          postgres://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/appdb?sslmode=disable
          {{- end }}
        # vault.hashicorp.com/agent-inject-command-tooling: |
        # vault.hashicorp.com/tls-secret: 'vault-tls-client'
    spec:
      containers:
        - name: app
          image: 'nginx:latest'
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: shared-secrets
            - mountPath: /tmp/vault
              name: vault-sink

      serviceAccountName: default
      volumes:
      - emptyDir:
          medium: Memory
        name: shared-secrets
      - emptyDir:
          medium: Memory
        name: vault-sink

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "webapp"
        }
        "mount_path" = "auth/aks-auth"
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/tmp/vault/sink"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    # "template" = {
    #   "contents" = "{{- with secret \"secret/database/creds/db-app\" -}}{{ range $k, $v := .Data.data }} export {{ $k }}="{{ $v }}" {{- end }}"
    #   "destination" = "/vault/secrets/db-creds"
    # }

    # "vault" = {
    #   "address" = "http://vault.vault.svc.cluster.local:8200"
    # }
    "vault" = {
      "address" = "http://52.185.214.2:8200"
    }

  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "webapp"
        }
        mount_path = "auth/aks-auth"
        "type" = "kubernetes"
      }
      "sink" = {
        "config" = {
          "path" = "/tmp/vault/sink"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      #"contents" = "{{- with secret \"secret/data/database/creds/db-app\" -}}{{ range $k, $v := .Data.data }}export {{ $k }}={{ $v }}{{ end }}{{- end }}"

      contents = <<EOT
        {{- with secret "secret/data/database/creds/db-app" -}}
          {{ range $k, $v := .Data.data }}
            export {{ $k }}={{ $v }}
          {{ end }}
        {{- end }}
      EOT

      "destination" = "/vault/secrets/db-creds"
    }

    # "vault" = {
    #   "address" = "http://vault.vault.svc.cluster.local:8200"
    # }
    "vault" = {
      "address" = "http://52.185.214.2:8200"
    }
